// --- 1. TU BASE DE DATOS REAL DE MUJER ---
const productosMujer = [
    { id: 1, nombre: "212 Tradicional", marca: "Carolina Herrera", precio: "380.000", img: "../img/212-dm.jpg" },
    { id: 2, nombre: "212 Vip", marca: "Carolina Herrera", precio: "410.000", img: "../img/212-vip-dm.jpg" },
    { id: 3, nombre: "212 Vip Rose", marca: "Carolina Herrera", precio: "420.000", img: "../img/212-rose.jpg" },
    { id: 4, nombre: "CH Pasión Women", marca: "Carolina Herrera", precio: "450.000", img: "../img/ch-pasion.jpg" },
    { id: 5, nombre: "Cloud Pink", marca: "Ariana Grande", precio: "320.000", img: "../img/cloud-pink.jpg" },
    { id: 6, nombre: "Ari EDP", marca: "Ariana Grande", precio: "290.000", img: "../img/ari.jpg" },
    { id: 7, nombre: "Cloud EDP", marca: "Ariana Grande", precio: "310.000", img: "../img/cloud.jpg" },
    { id: 8, nombre: "Mod Vanilla", marca: "Ariana Grande", precio: "330.000", img: "../img/mod-vanilla.jpg" },
    { id: 9, nombre: "Thank U Next", marca: "Ariana Grande", precio: "295.000", img: "../img/next.jpg" },
    { id: 10, nombre: "Sweet Like Candy", marca: "Ariana Grande", precio: "285.000", img: "../img/candy.jpg" },
    { id: 11, nombre: "Boucheron Femme", marca: "Boucheron", precio: "310.000", img: "../img/boucheron.jpg" },
    { id: 12, nombre: "Omnia Amethyste", marca: "Bulgari", precio: "340.000", img: "../img/omnia-a.jpg" },
    { id: 13, nombre: "Omnia Coral", marca: "Bulgari", precio: "340.000", img: "../img/omnia-c.jpg" },
    { id: 14, nombre: "Omnia Crystalline", marca: "Bulgari", precio: "340.000", img: "../img/omnia-cr.jpg" },
    { id: 15, nombre: "Coco Mademoiselle", marca: "Chanel", precio: "720.000", img: "../img/coco.jpg" },
    { id: 16, nombre: "Chanel N°5", marca: "Chanel", precio: "750.000", img: "../img/n5.jpg" },
    { id: 17, nombre: "Chance Eau Fraiche", marca: "Chanel", precio: "680.000", img: "../img/chance-f.jpg" },
    { id: 18, nombre: "Chance Eau Tendre", marca: "Chanel", precio: "680.000", img: "../img/chance-t.jpg" },
    { id: 19, nombre: "Miss Dior", marca: "Christian Dior", precio: "590.000", img: "../img/miss-dior.jpg" },
    { id: 20, nombre: "Jadore", marca: "Christian Dior", precio: "610.000", img: "../img/jadore.jpg" },
    { id: 21, nombre: "Hypnotic Poison", marca: "Christian Dior", precio: "480.000", img: "../img/hypnotic.jpg" },
    { id: 22, nombre: "Light Blue Dama", marca: "Dolce & Gabbana", precio: "320.000", img: "../img/lb-dm.jpg" },
    { id: 23, nombre: "Light Blue Intense", marca: "Dolce & Gabbana", precio: "390.000", img: "../img/lb-intense.jpg" },
    { id: 24, nombre: "Devotion Women", marca: "Dolce & Gabbana", precio: "460.000", img: "../img/devotion.jpg" },
    { id: 25, nombre: "L'Imperatrice", marca: "Dolce & Gabbana", precio: "280.000", img: "../img/imperatrice.jpg" },
    { id: 26, nombre: "Issey Miyake Dama", marca: "Issey Miyake", precio: "350.000", img: "../img/issey-dm.jpg" },
    { id: 27, nombre: "Scandal Dama", marca: "Jean Paul Gaultier", precio: "460.000", img: "../img/scandal-dm.jpg" },
    { id: 28, nombre: "Lacoste Sparkling", marca: "Lacoste", precio: "295.000", img: "../img/sparkling.jpg" },
    { id: 29, nombre: "Touch of Pink", marca: "Lacoste", precio: "270.000", img: "../img/pink.jpg" },
    { id: 30, nombre: "Magnetic Women", marca: "Lacoste", precio: "295.000", img: "../img/magnetic.jpg" },
    { id: 31, nombre: "Mont Blanc Individual", marca: "Mont Blanc", precio: "240.000", img: "../img/individual-dm.jpg" },
    { id: 32, nombre: "Mont Blanc Signature", marca: "Mont Blanc", precio: "310.000", img: "../img/signature.jpg" },
    { id: 33, nombre: "Fresh Pink", marca: "Moschino", precio: "260.000", img: "../img/fresh-pink.jpg" },
    { id: 34, nombre: "Moschino Funny", marca: "Moschino", precio: "220.000", img: "../img/funny.jpg" },
    { id: 35, nombre: "I Love Love", marca: "Moschino", precio: "230.000", img: "../img/ilove.jpg" },
    { id: 36, nombre: "Toy 2 (Osito Blanco)", marca: "Moschino", precio: "310.000", img: "../img/toy2.jpg" },
    { id: 37, nombre: "Toy 2 Bubble Gum", marca: "Moschino", precio: "290.000", img: "../img/bubble.jpg" },
    { id: 38, nombre: "Toy 2 Pearl", marca: "Moschino", precio: "330.000", img: "../img/pearl.jpg" },
    { id: 39, nombre: "Olympea", marca: "Paco Rabanne", precio: "395.000", img: "../img/olympea.jpg" },
    { id: 40, nombre: "Lady Million", marca: "Paco Rabanne", precio: "410.000", img: "../img/lady.jpg" },
    { id: 41, nombre: "Fame", marca: "Paco Rabanne", precio: "440.000", img: "../img/fame.jpg" },
    { id: 42, nombre: "Paris Hilton Tradicional", marca: "Paris Hilton", precio: "180.000", img: "../img/paris.jpg" },
    { id: 43, nombre: "Can Can", marca: "Paris Hilton", precio: "190.000", img: "../img/cancan.jpg" },
    { id: 44, nombre: "Tommy Dama", marca: "Tommy Hilfiger", precio: "195.000", img: "../img/tommy-dm.jpg" },
    { id: 45, nombre: "Tous Love Me", marca: "Tous", precio: "320.000", img: "../img/loveme.jpg" }
];